[package]
name = "avm1-parser-bin"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "avm1 parser"
documentation = "https://github.com/open-flash/avm1-parser"
homepage = "https://github.com/open-flash/avm1-parser"
repository = "https://github.com/open-flash/avm1-parser"
readme = "../README.md"
keywords = ["parser", "avm1", "flash"]
license = "AGPL-3.0-or-later"
edition = "2021"
rust-version = "1.60.0"

[[bin]]
name = "avm1-parser"
path = "src/main.rs"

[dependencies]
serde_json_v8 = "^0.1.1"
avm1-parser = { path = "../" }
avm1-types = "^0.14.0"
